spring.application.name=hospital-management

# =============================================================================
# CONEXÃO COM O BANCO DE DADOS POSTGRESQL
# =============================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=723213
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================================================
# CONFIGURAÇÕES DE INICIALIZAÇÃO DE DADOS (SEEDS)
# =============================================================================
# Força a execução dos scripts SQL (schema.sql / data.sql) mesmo com ddl-auto=none
spring.sql.init.mode=always
# Adiciona suporte para scripts com múltiplos blocos/instruções SQL se necessário
spring.sql.init.encoding=UTF-8

# =============================================================================
# CONFIGURAÇÕES DO SPRING DATA JPA / HIBERNATE
# =============================================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true