spring.application.name=hospital-management

# =============================================================================
# CONEXÃO COM O BANCO DE DADOS POSTGRESQL
# =============================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=723213
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================================================
# CONFIGURAÇÕES DE INICIALIZAÇÃO DE DADOS (SEEDS E DDL)
# =============================================================================
# Força a execução dos scripts SQL mesmo com ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# Ordem de execução: 1. Tabelas -> 2. Dados -> 3. Procedures/Triggers
spring.sql.init.data-locations=classpath:schemas.sql, classpath:data.sql, classpath:routines_and_triggers.sql

# Separador customizado para as Procedures
spring.sql.init.separator=^;

# =============================================================================
# CONFIGURAÇÕES DO SPRING DATA JPA / HIBERNATE
# =============================================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true